"""empty message

Revision ID: 3118d24d35af
Revises: 66877218d201
Create Date: 2024-04-28 12:30:05.952289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector

# revision identifiers, used by Alembic.
revision: str = '3118d24d35af'
down_revision: Union[str, None] = '66877218d201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'post')
    op.add_column('posts', sa.Column('embbedings', pgvector.sqlalchemy.Vector(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'embbedings')
    op.add_column('comments', sa.Column('post', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
