"""empty message

Revision ID: c8a87c8ed56d
Revises: d343c49caf87
Create Date: 2024-04-28 22:04:11.563904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c8a87c8ed56d'
down_revision: Union[str, None] = 'd343c49caf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Anonymous'"), nullable=False))
    op.drop_index('ix_users_Fullname', table_name='users')
    op.create_index(op.f('ix_users_fullname'), 'users', ['fullname'], unique=False)
    op.drop_column('users', 'Fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Fullname', sa.VARCHAR(), server_default=sa.text("'Anonymous'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_fullname'), table_name='users')
    op.create_index('ix_users_Fullname', 'users', ['Fullname'], unique=False)
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
