"""empty message

Revision ID: d343c49caf87
Revises: 147b11e54602
Create Date: 2024-04-28 22:01:19.427614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd343c49caf87'
down_revision: Union[str, None] = '147b11e54602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Fullname', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Anonymous'"), nullable=False))
    op.create_index(op.f('ix_users_Fullname'), 'users', ['Fullname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_Fullname'), table_name='users')
    op.drop_column('users', 'Fullname')
    # ### end Alembic commands ###
