"""empty message

Revision ID: edf70ca3dbd8
Revises: 7de312a231e7
Create Date: 2024-05-03 18:23:54.582915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'edf70ca3dbd8'
down_revision: Union[str, None] = '7de312a231e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topic_name', table_name='topic')
    op.drop_table('topic')
    op.drop_table('follows')
    op.drop_index('ix_embeddings_topic_id', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_comments_content', table_name='comments')
    op.drop_index('ix_comments_post_id', table_name='comments')
    op.drop_index('ix_comments_user_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_entryflags_entry_id', table_name='entryflags')
    op.drop_index('ix_entryflags_user_id', table_name='entryflags')
    op.drop_table('entryflags')
    op.drop_index('ix_userinfo_ext_id', table_name='userinfo')
    op.drop_table('userinfo')
    op.drop_index('ix_notifications_content', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_entry_author_id', table_name='entry')
    op.drop_index('ix_entry_topic_id', table_name='entry')
    op.drop_table('entry')
    op.drop_index('ix_author_user_id', table_name='author')
    op.drop_table('author')
    op.drop_index('ix_api_hug_user_id', table_name='api_hug')
    op.drop_table('api_hug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_hug',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], name='api_hug_user_id_fkey')
    )
    op.create_index('ix_api_hug_user_id', 'api_hug', ['user_id'], unique=True)
    op.create_table('author',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], name='author_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='author_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_author_user_id', 'author', ['user_id'], unique=True)
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('entry_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hidden', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.user_id'], name='entry_author_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='entry_topic_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entry_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_entry_topic_id', 'entry', ['topic_id'], unique=False)
    op.create_index('ix_entry_author_id', 'entry', ['author_id'], unique=False)
    op.create_table('notifications',
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], name='notifications_user_id_fkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=True)
    op.create_index('ix_notifications_content', 'notifications', ['content'], unique=False)
    op.create_table('userinfo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('userinfo_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('ext_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='userinfo_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_userinfo_ext_id', 'userinfo', ['ext_id'], unique=True)
    op.create_table('entryflags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], name='entryflags_entry_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], name='entryflags_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entryflags_pkey')
    )
    op.create_index('ix_entryflags_user_id', 'entryflags', ['user_id'], unique=False)
    op.create_index('ix_entryflags_entry_id', 'entryflags', ['entry_id'], unique=False)
    op.create_table('comments',
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['topic.id'], name='comments_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], name='comments_user_id_fkey')
    )
    op.create_index('ix_comments_user_id', 'comments', ['user_id'], unique=True)
    op.create_index('ix_comments_post_id', 'comments', ['post_id'], unique=True)
    op.create_index('ix_comments_content', 'comments', ['content'], unique=False)
    op.create_table('embeddings',
    sa.Column('embbedings', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='embeddings_topic_id_fkey')
    )
    op.create_index('ix_embeddings_topic_id', 'embeddings', ['topic_id'], unique=True)
    op.create_table('follows',
    sa.Column('followed_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('follower_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('followed_username', 'follower_username', name='follows_pkey')
    )
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topic_pkey')
    )
    op.create_index('ix_topic_name', 'topic', ['name'], unique=True)
    # ### end Alembic commands ###
